package db

import (
	"context"
	"fmt"
	"time"
)

// dbTimeLayouts lists the layouts we accept when reading datetime values back
// from SQLite. Writes are normalized to time.DateTime ("2006-01-02 15:04:05")
// UTC, which is also what CURRENT_TIMESTAMP produces; the extra layouts make
// reads resilient if a row was inserted by an older build or by hand.
var dbTimeLayouts = []string{
	time.DateTime, // 2006-01-02 15:04:05
	"2006-01-02 15:04:05.999999999-07:00",
	time.RFC3339Nano,
	time.RFC3339,
}

// parseDBTime parses a SQLite datetime string into a UTC time.Time. It returns
// the zero time when nothing matches; callers treat that as "unknown".
func parseDBTime(s string) time.Time {
	if s == "" {
		return time.Time{}
	}
	if t, err := time.Parse(time.DateTime, s); err == nil {
		return t.UTC()
	}
	for _, l := range dbTimeLayouts[1:] {
		if t, err := time.Parse(l, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

// fmtDBTime normalizes a time for storage. Zero times return nil so the
// column falls back to CURRENT_TIMESTAMP.
func fmtDBTime(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return t.UTC().Format(time.DateTime)
}

// RunRecord is the persisted form of an agent run reported via IPC or MCP.
// JSON tags make it directly serializable for the WebSocket stream.
type RunRecord struct {
	RunID            string    `json:"run_id"`
	TaskID           string    `json:"task_id"`
	AgentName        string    `json:"agent_name"`
	ModelName        string    `json:"model_name"`
	Provider         string    `json:"provider"`
	PromptTokens     int64     `json:"prompt_tokens"`
	CompletionTokens int64     `json:"completion_tokens"`
	CostUSD          float64   `json:"cost_usd"`
	Intent           string    `json:"intent"`
	CreatedAt        time.Time `json:"created_at"`
}

// EventRecord is the persisted form of a code_node_events row. Plain field
// types (no sql.Null*) keep JSON serialization clean; NULL handling happens
// locally inside the scan/insert helpers.
type EventRecord struct {
	EventID      string    `json:"event_id"`
	RunID        string    `json:"run_id"`
	RepoName     string    `json:"repo_name"`
	FilePath     string    `json:"file_path"`
	Signature    string    `json:"node_signature"`
	NodeType     string    `json:"node_type"`
	Action       string    `json:"action"`
	BodyHash     string    `json:"ast_content_hash"`
	LOC          int       `json:"lines_of_code"`
	StartLine    uint32    `json:"start_line"`
	EndLine      uint32    `json:"end_line"`
	DiffSnippet  string    `json:"diff_snippet"`
	AddedLines   int       `json:"added_lines"`
	DeletedLines int       `json:"deleted_lines"`
	OccurredAt   time.Time `json:"event_time"`
}

// UpsertRun inserts an agent_run, replacing any existing row with the same
// run_id. This makes IPC report retries idempotent.
func (s *Store) UpsertRun(r RunRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	const q = `
		INSERT INTO agent_runs (run_id, task_id, agent_name, model_name, provider,
			prompt_tokens, completion_tokens, cost_usd, intent, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
		ON CONFLICT(run_id) DO UPDATE SET
			task_id           = excluded.task_id,
			agent_name        = excluded.agent_name,
			model_name        = excluded.model_name,
			provider          = excluded.provider,
			prompt_tokens     = excluded.prompt_tokens,
			completion_tokens = excluded.completion_tokens,
			cost_usd          = excluded.cost_usd,
			intent            = excluded.intent
	`
	_, err := s.db.ExecContext(ctx, q,
		r.RunID, r.TaskID, r.AgentName, r.ModelName, r.Provider,
		r.PromptTokens, r.CompletionTokens, r.CostUSD, r.Intent, fmtDBTime(r.CreatedAt),
	)
	if err != nil {
		return fmt.Errorf("upsert run %s: %w", r.RunID, err)
	}
	return nil
}

// InsertEvent appends one code_node_events row. EventID is generated by the
// caller so it can pre-emit the event on the websocket stream and reconcile
// DB-side failures with the client.
func (s *Store) InsertEvent(e EventRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	const q = `
		INSERT INTO code_node_events
			(event_id, run_id, repo_name, file_path, node_signature, node_type, action,
			 ast_content_hash, lines_of_code, start_line, end_line, diff_snippet,
			 added_lines, deleted_lines, event_time)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
	`
	var runID any
	if e.RunID != "" {
		runID = e.RunID
	}
	var bodyHash any
	if e.BodyHash != "" {
		bodyHash = e.BodyHash
	}
	_, err := s.db.ExecContext(ctx, q,
		e.EventID, runID, e.RepoName, e.FilePath, e.Signature, e.NodeType,
		e.Action, bodyHash, e.LOC, e.StartLine, e.EndLine, e.DiffSnippet,
		e.AddedLines, e.DeletedLines, fmtDBTime(e.OccurredAt),
	)
	if err != nil {
		return fmt.Errorf("insert event %s: %w", e.EventID, err)
	}
	return nil
}

// RecentEvents returns the N most recent events for the live feed.
func (s *Store) RecentEvents(limit int) ([]EventRecord, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := s.db.QueryContext(context.Background(), `
		SELECT event_id, run_id, repo_name, file_path, node_signature, node_type,
		       action, ast_content_hash, lines_of_code,
		       COALESCE(start_line, 0), COALESCE(end_line, 0), COALESCE(diff_snippet, ''),
		       COALESCE(added_lines, 0), COALESCE(deleted_lines, 0), event_time
		FROM code_node_events
		ORDER BY event_time DESC
		LIMIT ?
	`, limit)
	if err != nil {
		return nil, fmt.Errorf("recent events: %w", err)
	}
	defer rows.Close()

	out := make([]EventRecord, 0, limit)
	for rows.Next() {
		var (
			e        EventRecord
			ts       string
			runID    = nullable(&e.RunID)
			bodyHash = nullable(&e.BodyHash)
		)
		if err := rows.Scan(&e.EventID, runID, &e.RepoName, &e.FilePath,
			&e.Signature, &e.NodeType, &e.Action, bodyHash, &e.LOC,
			&e.StartLine, &e.EndLine, &e.DiffSnippet, &e.AddedLines, &e.DeletedLines, &ts); err != nil {
			return nil, fmt.Errorf("scan recent event: %w", err)
		}
		e.OccurredAt = parseDBTime(ts)
		out = append(out, e)
	}
	return out, rows.Err()
}

// ThrashingRow is a single entry in the thrashing heatmap.
type ThrashingRow struct {
	FilePath    string    `json:"file_path"`
	Signature   string    `json:"node_signature"`
	EditCount   int       `json:"edit_count"`
	FirstEvent  time.Time `json:"first_event"`
	LastEvent   time.Time `json:"last_event"`
	WindowHours float64   `json:"window_hours"`
}

// Thrashing finds (file, node) pairs edited at least minEdits times within a
// rolling 24-hour window, looking back lookbackDays. The hour span is computed
// in Go because SQLite lacks DATE_DIFF; this keeps the SQL portable.
func (s *Store) Thrashing(minEdits int, lookbackDays int) ([]ThrashingRow, error) {
	if minEdits <= 0 {
		minEdits = 3
	}
	if lookbackDays <= 0 {
		lookbackDays = 7
	}

	rows, err := s.db.QueryContext(context.Background(), `
		SELECT file_path, node_signature, COUNT(*) AS edit_count,
		       MIN(event_time) AS first_event, MAX(event_time) AS last_event
		FROM code_node_events
		WHERE event_time >= datetime('now', ?)
		GROUP BY file_path, node_signature
		HAVING edit_count >= ?
		ORDER BY edit_count DESC
		LIMIT 100
	`, fmt.Sprintf("-%d days", lookbackDays), minEdits)
	if err != nil {
		return nil, fmt.Errorf("thrashing query: %w", err)
	}
	defer rows.Close()

	var out []ThrashingRow
	for rows.Next() {
		var (
			r         ThrashingRow
			first, last string
		)
		if err := rows.Scan(&r.FilePath, &r.Signature, &r.EditCount, &first, &last); err != nil {
			return nil, fmt.Errorf("scan thrashing: %w", err)
		}
		r.FirstEvent = parseDBTime(first)
		r.LastEvent = parseDBTime(last)
		span := r.LastEvent.Sub(r.FirstEvent).Hours()
		if span < 0 {
			span = 0
		}
		r.WindowHours = span
		if r.EditCount >= minEdits && span <= 24 {
			out = append(out, r)
		}
	}
	return out, rows.Err()
}

// ModelRow aggregates per-model stats: survival, longevity, cost, and ROI.
// RunCount counts agent_runs rows; a model with runs but no correlated events
// appears here with TotalNodes = 0 and its spend already visible.
type ModelRow struct {
	Model              string  `json:"model"`
	TotalNodes         int     `json:"total_nodes"`
	ActiveNodes        int     `json:"active_nodes"`
	SurvivalRatePct    float64 `json:"survival_rate_pct"`
	AvgLongevityDays   float64 `json:"avg_longevity_days"`
	TotalCostUSD       float64 `json:"total_cost_usd"`
	TotalSurvivedNodes int     `json:"total_survived_nodes"`
	CostPerSurvNode    float64 `json:"cost_per_surviving_node"`
	RunCount           int     `json:"run_count"`
}

// ModelComparison computes per-model survival and ROI for every model the
// daemon has ever seen — i.e. the union of models in agent_runs and models
// credited with code_node_events. Driving from this universe (rather than
// from events alone) means reported spend is visible immediately, before any
// code churn has been correlated. Total cost always sums agent_runs; ROI
// (cost per survived node) stays undefined until a node survives 14+ days.
func (s *Store) ModelComparison() ([]ModelRow, error) {
	rows, err := s.db.QueryContext(context.Background(), `
		WITH lifecycle AS (
			SELECT e.node_signature,
			       COALESCE(r.model_name, 'unknown') AS model_name,
			       MIN(e.event_time) AS birth_time,
			       MAX(CASE WHEN e.action = 'DELETED' THEN e.event_time END) AS death_time
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			GROUP BY e.node_signature, COALESCE(r.model_name, 'unknown')
		),
		lc AS (
			SELECT model_name,
			       COUNT(*) AS total_nodes,
			       SUM(CASE WHEN death_time IS NULL THEN 1 ELSE 0 END) AS active_nodes,
			       AVG(julianday(COALESCE(death_time, CURRENT_TIMESTAMP)) - julianday(birth_time)) AS avg_longevity
			FROM lifecycle
			GROUP BY model_name
		),
		roi AS (
			SELECT COALESCE(r.model_name, 'unknown') AS model_name,
			       COUNT(DISTINCT e.node_signature) AS survived_count
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE e.action = 'ADDED'
			  AND e.event_time <= datetime('now', '-14 days')
			  AND e.node_signature NOT IN (SELECT node_signature FROM code_node_events WHERE action = 'DELETED')
			GROUP BY COALESCE(r.model_name, 'unknown')
		),
		spend AS (
			SELECT model_name,
			       SUM(COALESCE(cost_usd, 0)) AS total_cost,
			       COUNT(*)                  AS run_count
			FROM agent_runs
			WHERE model_name IS NOT NULL AND model_name <> ''
			GROUP BY model_name
		),
		models AS (
			SELECT model_name FROM lc
			UNION
			SELECT model_name FROM spend
		)
		SELECT m.model_name,
		       COALESCE(lc.total_nodes, 0),
		       COALESCE(lc.active_nodes, 0),
		       COALESCE(lc.avg_longevity, 0),
		       COALESCE(spend.total_cost, 0),
		       COALESCE(roi.survived_count, 0),
		       COALESCE(spend.run_count, 0)
		FROM models m
		LEFT JOIN lc    ON lc.model_name    = m.model_name
		LEFT JOIN roi   ON roi.model_name   = m.model_name
		LEFT JOIN spend ON spend.model_name = m.model_name
		ORDER BY m.model_name
	`)
	if err != nil {
		return nil, fmt.Errorf("model comparison: %w", err)
	}
	defer rows.Close()

	var out []ModelRow
	for rows.Next() {
		var (
			r      ModelRow
			active any
			lon    any
		)
		if err := rows.Scan(&r.Model, &r.TotalNodes, &active, &lon, &r.TotalCostUSD, &r.TotalSurvivedNodes, &r.RunCount); err != nil {
			return nil, fmt.Errorf("scan model row: %w", err)
		}
		r.ActiveNodes = toInt(active)
		r.AvgLongevityDays = toFloat(lon)
		if r.TotalNodes > 0 {
			r.SurvivalRatePct = float64(r.ActiveNodes) * 100 / float64(r.TotalNodes)
		}
		if r.TotalSurvivedNodes > 0 {
			r.CostPerSurvNode = r.TotalCostUSD / float64(r.TotalSurvivedNodes)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// FileHealth is the result of get_file_health_score: a 0..100 score (higher =
// healthier) plus a fragility flag derived from the last 24h of edits.
type FileHealth struct {
	FilePath             string `json:"file_path"`
	HealthScore          int    `json:"health_score"`
	IsFragile            bool   `json:"is_fragile"`
	RecentThrashingCount int    `json:"recent_thrashing_count"`
	Warning              string `json:"warning"`
}

// FileHealth scores a file for agent guardrails: -8 per edit in the last 24h,
// -5 extra when 3+ distinct signatures churned, fragile at >= 5 edits.
func (s *Store) FileHealth(filePath string) (FileHealth, error) {
	out := FileHealth{FilePath: filePath, HealthScore: 100}

	var edits, sigs int
	row := s.db.QueryRowContext(context.Background(), `
		SELECT COUNT(*), COUNT(DISTINCT node_signature)
		FROM code_node_events
		WHERE file_path = ?
		  AND event_time >= datetime('now', '-1 day')
	`, filePath)
	if err := row.Scan(&edits, &sigs); err != nil {
		return out, fmt.Errorf("file health scan: %w", err)
	}
	out.RecentThrashingCount = edits

	penalty := edits * 8
	if sigs >= 3 {
		penalty += 5
	}
	if penalty > 100 {
		penalty = 100
	}
	out.HealthScore = 100 - penalty
	if edits >= 5 {
		out.IsFragile = true
		out.Warning = fmt.Sprintf("%d edits in the last 24h across %d signatures", edits, sigs)
	}
	return out, nil
}

// NodeStat captures aggregate historical stats for a single node signature.
type NodeStat struct {
	Signature   string    `json:"node_signature"`
	FilePath    string    `json:"file_path"`
	EditCount   int       `json:"edit_count"`
	LastAction  string    `json:"last_action"`
	LastModel   string    `json:"last_model"`
	LastEventAt time.Time `json:"last_event_time"`
}

// AllNodeStats queries aggregate metrics for every known AST node signature.
func (s *Store) AllNodeStats() (map[string]NodeStat, error) {
	rows, err := s.db.QueryContext(context.Background(), `
		SELECT e.node_signature, e.file_path, COUNT(*) as edit_count,
		       COALESCE((SELECT action FROM code_node_events WHERE node_signature = e.node_signature ORDER BY event_time DESC LIMIT 1), 'ACTIVE') as last_action,
		       COALESCE((SELECT r.model_name FROM code_node_events c LEFT JOIN agent_runs r ON c.run_id = r.run_id WHERE c.node_signature = e.node_signature AND r.model_name IS NOT NULL ORDER BY c.event_time DESC LIMIT 1), 'unknown') as last_model,
		       MAX(e.event_time) as last_event_time
		FROM code_node_events e
		GROUP BY e.node_signature, e.file_path
	`)
	if err != nil {
		return nil, fmt.Errorf("node stats query: %w", err)
	}
	defer rows.Close()

	out := make(map[string]NodeStat)
	for rows.Next() {
		var ns NodeStat
		var ts string
		if err := rows.Scan(&ns.Signature, &ns.FilePath, &ns.EditCount, &ns.LastAction, &ns.LastModel, &ts); err != nil {
			return nil, fmt.Errorf("scan node stat: %w", err)
		}
		ns.LastEventAt = parseDBTime(ts)
		out[ns.Signature] = ns
	}
	return out, rows.Err()
}

// nullable returns a sql.Scanner that writes through to s when the column is
// NULL-safe (empty string means NULL in our schema).
func nullable(s *string) *nullString { return &nullString{s: s} }

type nullString struct{ s *string }

func (n *nullString) Scan(v any) error {
	if v == nil {
		*n.s = ""
		return nil
	}
	switch t := v.(type) {
	case string:
		*n.s = t
	case []byte:
		*n.s = string(t)
	default:
		return fmt.Errorf("nullString: unsupported type %T", v)
	}
	return nil
}

func toInt(v any) int {
	switch t := v.(type) {
	case int64:
		return int(t)
	case int:
		return t
	case float64:
		return int(t)
	}
	return 0
}

func toFloat(v any) float64 {
	switch t := v.(type) {
	case float64:
		return t
	case int64:
		return float64(t)
	case int:
		return float64(t)
	}
	return 0
}
