package db

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/wrongstack/wrongtrace/internal/models"
)

// dbTimeLayouts lists the layouts we accept when reading datetime values back
// from SQLite. Writes are normalized to time.DateTime ("2006-01-02 15:04:05")
// UTC, which is also what CURRENT_TIMESTAMP produces; the extra layouts make
// reads resilient if a row was inserted by an older build or by hand.
var dbTimeLayouts = []string{
	time.DateTime, // 2006-01-02 15:04:05
	"2006-01-02 15:04:05.999999999-07:00",
	time.RFC3339Nano,
	time.RFC3339,
}

// parseDBTime parses a SQLite datetime string into a UTC time.Time. It returns
// the zero time when nothing matches; callers treat that as "unknown".
func parseDBTime(s string) time.Time {
	if s == "" {
		return time.Time{}
	}
	if t, err := time.Parse(time.DateTime, s); err == nil {
		return t.UTC()
	}
	for _, l := range dbTimeLayouts[1:] {
		if t, err := time.Parse(l, s); err == nil {
			return t.UTC()
		}
	}
	return time.Time{}
}

// fmtDBTime normalizes a time for storage. Zero times return nil so the
// column falls back to CURRENT_TIMESTAMP.
func fmtDBTime(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return t.UTC().Format(time.DateTime)
}

// RunRecord is the persisted form of an agent run reported via IPC or MCP.
// JSON tags make it directly serializable for the WebSocket stream.
type RunRecord struct {
	RunID            string    `json:"run_id"`
	TaskID           string    `json:"task_id"`
	AgentName        string    `json:"agent_name"`
	ModelName        string    `json:"model_name"`
	Provider         string    `json:"provider"`
	PromptTokens     int64     `json:"prompt_tokens"`
	CompletionTokens int64     `json:"completion_tokens"`
	CostUSD          float64   `json:"cost_usd"`
	Intent           string    `json:"intent"`
	CreatedAt        time.Time `json:"created_at"`
}

// EventRecord is the persisted form of a code_node_events row. Plain field
// types (no sql.Null*) keep JSON serialization clean; NULL handling happens
// locally inside the scan/insert helpers.
type EventRecord struct {
	EventID      string    `json:"event_id"`
	RunID        string    `json:"run_id"`
	RepoName     string    `json:"repo_name"`
	FilePath     string    `json:"file_path"`
	Signature    string    `json:"node_signature"`
	NodeType     string    `json:"node_type"`
	Action       string    `json:"action"`
	BodyHash     string    `json:"ast_content_hash"`
	LOC          int       `json:"lines_of_code"`
	StartLine    uint32    `json:"start_line"`
	EndLine      uint32    `json:"end_line"`
	DiffSnippet  string    `json:"diff_snippet"`
	AddedLines   int       `json:"added_lines"`
	DeletedLines int       `json:"deleted_lines"`
	AuthorModel  string    `json:"author_model,omitempty"`
	OccurredAt   time.Time `json:"event_time"`
	Timestamp    time.Time `json:"timestamp,omitempty"`
}

// UpsertRun inserts an agent_run, replacing any existing row with the same
// run_id. This makes IPC report retries idempotent.
func (s *Store) UpsertRun(r RunRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	const q = `
		INSERT INTO agent_runs (run_id, task_id, agent_name, model_name, provider,
			prompt_tokens, completion_tokens, cost_usd, intent, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
		ON CONFLICT(run_id) DO UPDATE SET
			task_id           = excluded.task_id,
			agent_name        = excluded.agent_name,
			model_name        = excluded.model_name,
			provider          = excluded.provider,
			prompt_tokens     = excluded.prompt_tokens,
			completion_tokens = excluded.completion_tokens,
			cost_usd          = excluded.cost_usd,
			intent            = excluded.intent
	`
	_, err := s.db.ExecContext(ctx, q,
		r.RunID, r.TaskID, r.AgentName, r.ModelName, r.Provider,
		r.PromptTokens, r.CompletionTokens, r.CostUSD, r.Intent, fmtDBTime(r.CreatedAt),
	)
	if err != nil {
		return fmt.Errorf("upsert run %s: %w", r.RunID, err)
	}
	return nil
}

// InsertEvent appends one code_node_events row. EventID is generated by the
// caller so it can pre-emit the event on the websocket stream and reconcile
// DB-side failures with the client.
func (s *Store) InsertEvent(e EventRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	const q = `
		INSERT INTO code_node_events
			(event_id, run_id, repo_name, file_path, node_signature, node_type, action,
			 ast_content_hash, lines_of_code, start_line, end_line, diff_snippet,
			 added_lines, deleted_lines, event_time)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
	`
	var runID any
	if e.RunID != "" {
		runID = e.RunID
	}
	var bodyHash any
	if e.BodyHash != "" {
		bodyHash = e.BodyHash
	}
	_, err := s.db.ExecContext(ctx, q,
		e.EventID, runID, e.RepoName, e.FilePath, e.Signature, e.NodeType,
		e.Action, bodyHash, e.LOC, e.StartLine, e.EndLine, e.DiffSnippet,
		e.AddedLines, e.DeletedLines, fmtDBTime(e.OccurredAt),
	)
	if err != nil {
		return fmt.Errorf("insert event %s: %w", e.EventID, err)
	}
	return nil
}

// RecentEvents returns the N most recent events for the live feed, optionally filtered by repo_name.
func (s *Store) RecentEvents(limit int, repoFilter ...string) ([]EventRecord, error) {
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}
	return s.RecentEventsFiltered(limit, repo, "", time.Time{})
}

// RecentFileEvents returns the N most recent AST events specifically matching a file path.
func (s *Store) RecentFileEvents(filePath string, limit int) ([]EventRecord, error) {
	return s.RecentEventsFiltered(limit, "", filePath, time.Time{})
}

// RecentEventsFiltered queries recent AST and code mutation events with flexible filtering.
func (s *Store) RecentEventsFiltered(limit int, repo string, filePath string, since time.Time) ([]EventRecord, error) {
	if limit <= 0 {
		limit = 50
	}
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	var whereClauses []string
	var args []any

	if repo != "" && repo != "all" && repo != "*" {
		whereClauses = append(whereClauses, "(LOWER(e.repo_name) = LOWER(?) OR e.repo_name = '' OR e.repo_name IS NULL)")
		args = append(args, repo)
	}

	if filePath != "" {
		normSlash := strings.ReplaceAll(strings.TrimSpace(filePath), "\\", "/")
		normSlash = strings.TrimPrefix(normSlash, "./")
		whereClauses = append(whereClauses, "(e.file_path = ? OR REPLACE(e.file_path, '\\', '/') = ? OR REPLACE(e.file_path, '\\', '/') LIKE '%' || ? OR ? LIKE '%' || REPLACE(e.file_path, '\\', '/') OR LOWER(REPLACE(e.file_path, '\\', '/')) LIKE '%' || LOWER(?))")
		args = append(args, filePath, normSlash, normSlash, normSlash, normSlash)
	}

	if !since.IsZero() {
		whereClauses = append(whereClauses, "e.event_time >= ?")
		args = append(args, since.UTC().Format("2006-01-02 15:04:05"))
	}

	whereSQL := ""
	if len(whereClauses) > 0 {
		whereSQL = "WHERE " + strings.Join(whereClauses, " AND ")
	}

	query := fmt.Sprintf(`
		SELECT e.event_id, COALESCE(e.run_id, ''), e.repo_name, e.file_path, e.node_signature, e.node_type,
		       e.action, COALESCE(e.ast_content_hash, ''), e.lines_of_code,
		       COALESCE(e.start_line, 0), COALESCE(e.end_line, 0), COALESCE(e.diff_snippet, ''),
		       COALESCE(e.added_lines, 0), COALESCE(e.deleted_lines, 0), e.event_time,
		       COALESCE(r.model_name, 'unknown') AS author_model
		FROM code_node_events e
		LEFT JOIN agent_runs r ON e.run_id = r.run_id
		%s
		ORDER BY e.event_time DESC
		LIMIT ?
	`, whereSQL)
	args = append(args, limit)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("recent events: %w", err)
	}
	defer rows.Close()

	out := make([]EventRecord, 0, limit)
	for rows.Next() {
		var (
			e        EventRecord
			ts       string
			runID    = nullable(&e.RunID)
			bodyHash = nullable(&e.BodyHash)
		)
		if err := rows.Scan(&e.EventID, runID, &e.RepoName, &e.FilePath,
			&e.Signature, &e.NodeType, &e.Action, bodyHash, &e.LOC,
			&e.StartLine, &e.EndLine, &e.DiffSnippet, &e.AddedLines, &e.DeletedLines, &ts,
			&e.AuthorModel); err != nil {
			return nil, fmt.Errorf("scan recent event: %w", err)
		}
		e.OccurredAt = parseDBTime(ts)
		e.Timestamp = e.OccurredAt
		out = append(out, e)
	}
	return out, rows.Err()
}

// ThrashingRow is a single entry in the thrashing heatmap.
type ThrashingRow struct {
	FilePath    string    `json:"file_path"`
	Signature   string    `json:"node_signature"`
	EditCount   int       `json:"edit_count"`
	FirstEvent  time.Time `json:"first_event"`
	LastEvent   time.Time `json:"last_event"`
	WindowHours float64   `json:"window_hours"`
}

// Thrashing finds (file, node) pairs edited at least minEdits times within a
// rolling 24-hour window, looking back lookbackDays, optionally filtered by repo_name.
func (s *Store) Thrashing(minEdits int, lookbackDays int, repoFilter ...string) ([]ThrashingRow, error) {
	if minEdits <= 0 {
		minEdits = 3
	}
	if lookbackDays <= 0 {
		lookbackDays = 7
	}
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}

	var query string
	var args []any
	if repo == "" {
		query = `
			SELECT file_path, node_signature, COUNT(*) AS edit_count,
			       MIN(event_time) AS first_event, MAX(event_time) AS last_event
			FROM code_node_events
			WHERE event_time >= datetime('now', ?)
			GROUP BY file_path, node_signature
			HAVING edit_count >= ? AND (julianday(MAX(event_time)) - julianday(MIN(event_time))) <= 1.0
			ORDER BY edit_count DESC
			LIMIT 100
		`
		args = []any{fmt.Sprintf("-%d days", lookbackDays), minEdits}
	} else {
		query = `
			SELECT file_path, node_signature, COUNT(*) AS edit_count,
			       MIN(event_time) AS first_event, MAX(event_time) AS last_event
			FROM code_node_events
			WHERE event_time >= datetime('now', ?) AND (repo_name = ? OR repo_name = '' OR repo_name IS NULL)
			GROUP BY file_path, node_signature
			HAVING edit_count >= ? AND (julianday(MAX(event_time)) - julianday(MIN(event_time))) <= 1.0
			ORDER BY edit_count DESC
			LIMIT 100
		`
		args = []any{fmt.Sprintf("-%d days", lookbackDays), repo, minEdits}
	}

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("thrashing query: %w", err)
	}
	defer rows.Close()

	var out []ThrashingRow
	for rows.Next() {
		var (
			r           ThrashingRow
			first, last string
		)
		if err := rows.Scan(&r.FilePath, &r.Signature, &r.EditCount, &first, &last); err != nil {
			return nil, fmt.Errorf("scan thrashing: %w", err)
		}
		r.FirstEvent = parseDBTime(first)
		r.LastEvent = parseDBTime(last)
		span := r.LastEvent.Sub(r.FirstEvent).Hours()
		if span < 0 {
			span = 0
		}
		r.WindowHours = span
		if r.EditCount >= minEdits && span <= 24.0+1e-4 {
			out = append(out, r)
		}
	}
	return out, rows.Err()
}

// ModelRow aggregates per-model stats: survival, longevity, cost, and ROI.
// RunCount counts agent_runs rows; a model with runs but no correlated events
// appears here with TotalNodes = 0 and its spend already visible.
type ModelRow struct {
	Model              string  `json:"model"`
	TotalNodes         int     `json:"total_nodes"`
	ActiveNodes        int     `json:"active_nodes"`
	SurvivalRatePct    float64 `json:"survival_rate_pct"`
	AvgLongevityDays   float64 `json:"avg_longevity_days"`
	TotalCostUSD       float64 `json:"total_cost_usd"`
	TotalSurvivedNodes int     `json:"total_survived_nodes"`
	CostPerSurvNode    float64 `json:"cost_per_surviving_node"`
	RunCount           int     `json:"run_count"`
}

// ModelComparison computes per-model survival and ROI for every model the
// daemon has ever seen, optionally filtered by repo_name.
func (s *Store) ModelComparison(repoFilter ...string) ([]ModelRow, error) {
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}

	var query string
	var args []any
	if repo == "" {
		query = `
		WITH lifecycle AS (
			SELECT e.node_signature,
			       COALESCE(r.model_name, 'unknown') AS model_name,
			       MIN(e.event_time) AS birth_time,
			       MAX(CASE WHEN e.action = 'DELETED' THEN e.event_time END) AS death_time,
			       MAX(e.event_time) AS last_event_time
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			GROUP BY e.node_signature, COALESCE(r.model_name, 'unknown')
		),
		lc AS (
			SELECT model_name,
			       COUNT(*) AS total_nodes,
			       SUM(CASE WHEN death_time IS NULL OR last_event_time > death_time THEN 1 ELSE 0 END) AS active_nodes,
			       AVG(julianday(COALESCE(CASE WHEN last_event_time > death_time THEN NULL ELSE death_time END, CURRENT_TIMESTAMP)) - julianday(birth_time)) AS avg_longevity
			FROM lifecycle
			GROUP BY model_name
		),
		roi AS (
			SELECT COALESCE(r.model_name, 'unknown') AS model_name,
			       COUNT(DISTINCT e.node_signature) AS survived_count
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE e.action = 'ADDED'
			  AND e.event_time <= datetime('now', '-14 days')
			  AND e.node_signature NOT IN (SELECT node_signature FROM code_node_events WHERE action = 'DELETED')
			GROUP BY COALESCE(r.model_name, 'unknown')
		),
		spend AS (
			SELECT model_name,
			       SUM(COALESCE(cost_usd, 0)) AS total_cost,
			       COUNT(*)                  AS run_count
			FROM agent_runs
			WHERE model_name IS NOT NULL AND model_name <> ''
			GROUP BY model_name
		),
		models AS (
			SELECT model_name FROM lc
			UNION
			SELECT model_name FROM spend
		)
		SELECT m.model_name,
		       COALESCE(lc.total_nodes, 0),
		       COALESCE(lc.active_nodes, 0),
		       COALESCE(lc.avg_longevity, 0),
		       COALESCE(spend.total_cost, 0),
		       COALESCE(roi.survived_count, 0),
		       COALESCE(spend.run_count, 0)
		FROM models m
		LEFT JOIN lc    ON lc.model_name    = m.model_name
		LEFT JOIN roi   ON roi.model_name   = m.model_name
		LEFT JOIN spend ON spend.model_name = m.model_name
		ORDER BY m.model_name
		`
		args = []any{}
	} else {
		query = `
		WITH lifecycle AS (
			SELECT e.node_signature,
			       COALESCE(r.model_name, 'unknown') AS model_name,
			       MIN(e.event_time) AS birth_time,
			       MAX(CASE WHEN e.action = 'DELETED' THEN e.event_time END) AS death_time,
			       MAX(e.event_time) AS last_event_time
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE (e.repo_name = ? OR e.repo_name = '' OR e.repo_name IS NULL)
			GROUP BY e.node_signature, COALESCE(r.model_name, 'unknown')
		),
		lc AS (
			SELECT model_name,
			       COUNT(*) AS total_nodes,
			       SUM(CASE WHEN death_time IS NULL OR last_event_time > death_time THEN 1 ELSE 0 END) AS active_nodes,
			       AVG(julianday(COALESCE(CASE WHEN last_event_time > death_time THEN NULL ELSE death_time END, CURRENT_TIMESTAMP)) - julianday(birth_time)) AS avg_longevity
			FROM lifecycle
			GROUP BY model_name
		),
		roi AS (
			SELECT COALESCE(r.model_name, 'unknown') AS model_name,
			       COUNT(DISTINCT e.node_signature) AS survived_count
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE (e.repo_name = ? OR e.repo_name = '' OR e.repo_name IS NULL)
			  AND e.action = 'ADDED'
			  AND e.event_time <= datetime('now', '-14 days')
			  AND e.node_signature NOT IN (SELECT node_signature FROM code_node_events WHERE (repo_name = ? OR repo_name = '' OR repo_name IS NULL) AND action = 'DELETED')
			GROUP BY COALESCE(r.model_name, 'unknown')
		),
		spend AS (
			SELECT model_name,
			       SUM(COALESCE(cost_usd, 0)) AS total_cost,
			       COUNT(*)                  AS run_count
			FROM agent_runs r
			WHERE model_name IS NOT NULL AND model_name <> ''
			  AND (r.run_id IN (
				SELECT DISTINCT run_id FROM code_node_events WHERE (repo_name = ? OR repo_name = '' OR repo_name IS NULL) AND run_id IS NOT NULL
				UNION
				SELECT DISTINCT run_id FROM file_read_events WHERE (repo_name = ? OR repo_name = '' OR repo_name IS NULL) AND run_id IS NOT NULL
			  ) OR NOT EXISTS (SELECT 1 FROM code_node_events WHERE repo_name != ? AND repo_name != '' AND repo_name IS NOT NULL))
			GROUP BY model_name
		),
		models AS (
			SELECT model_name FROM lc
			UNION
			SELECT model_name FROM spend
		)
		SELECT m.model_name,
		       COALESCE(lc.total_nodes, 0),
		       COALESCE(lc.active_nodes, 0),
		       COALESCE(lc.avg_longevity, 0),
		       COALESCE(spend.total_cost, 0),
		       COALESCE(roi.survived_count, 0),
		       COALESCE(spend.run_count, 0)
		FROM models m
		LEFT JOIN lc    ON lc.model_name    = m.model_name
		LEFT JOIN roi   ON roi.model_name   = m.model_name
		LEFT JOIN spend ON spend.model_name = m.model_name
		ORDER BY m.model_name
		`
		args = []any{repo, repo, repo, repo, repo, repo}
	}

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("model comparison: %w", err)
	}
	defer rows.Close()

	var out []ModelRow
	for rows.Next() {
		var (
			r      ModelRow
			active any
			lon    any
		)
		if err := rows.Scan(&r.Model, &r.TotalNodes, &active, &lon, &r.TotalCostUSD, &r.TotalSurvivedNodes, &r.RunCount); err != nil {
			return nil, fmt.Errorf("scan model row: %w", err)
		}
		if models.IsJunkModel(r.Model) {
			continue
		}
		r.ActiveNodes = toInt(active)
		r.AvgLongevityDays = toFloat(lon)
		if r.TotalNodes > 0 {
			r.SurvivalRatePct = float64(r.ActiveNodes) * 100 / float64(r.TotalNodes)
		}
		if r.TotalSurvivedNodes > 0 {
			r.CostPerSurvNode = r.TotalCostUSD / float64(r.TotalSurvivedNodes)
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// FileHealth is the result of get_file_health_score: a 0..100 score (higher =
// healthier) plus a fragility flag derived from the last 24h of edits.
type FileHealth struct {
	FilePath             string `json:"file_path"`
	HealthScore          int    `json:"health_score"`
	IsFragile            bool   `json:"is_fragile"`
	RecentThrashingCount int    `json:"recent_thrashing_count"`
	Warning              string `json:"warning"`
}

// FileHealth scores a file for agent guardrails: -8 per edit in the last 24h,
// -5 extra when 3+ distinct signatures churned, fragile at >= 5 edits.
func (s *Store) FileHealth(filePath string) (FileHealth, error) {
	out := FileHealth{FilePath: filePath, HealthScore: 100}

	var edits, sigs int
	normSlash := strings.ReplaceAll(filePath, "\\", "/")
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	row := s.db.QueryRowContext(ctx, `
		SELECT COUNT(*), COUNT(DISTINCT node_signature)
		FROM code_node_events
		WHERE (file_path = ? OR REPLACE(file_path, '\', '/') = ? OR REPLACE(file_path, '\', '/') LIKE '%/' || ?)
		  AND event_time >= datetime('now', '-1 day')
	`, filePath, normSlash, normSlash)
	if err := row.Scan(&edits, &sigs); err != nil {
		return out, fmt.Errorf("file health scan: %w", err)
	}
	out.RecentThrashingCount = edits

	penalty := edits * 8
	if sigs >= 3 {
		penalty += 5
	}
	if penalty > 100 {
		penalty = 100
	}
	out.HealthScore = 100 - penalty
	if edits >= 5 {
		out.IsFragile = true
		out.Warning = fmt.Sprintf("%d edits in the last 24h across %d signatures", edits, sigs)
	}
	return out, nil
}

// AllFilesHealth queries health scores for all churned files, optionally filtered by repo_name.
func (s *Store) AllFilesHealth(repoFilter ...string) (map[string]FileHealth, error) {
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}

	var query string
	var args []any
	if repo == "" {
		query = `
			SELECT file_path, COUNT(*), COUNT(DISTINCT node_signature)
			FROM code_node_events
			WHERE event_time >= datetime('now', '-1 day')
			GROUP BY file_path
		`
		args = []any{}
	} else {
		query = `
			SELECT file_path, COUNT(*), COUNT(DISTINCT node_signature)
			FROM code_node_events
			WHERE event_time >= datetime('now', '-1 day') AND (repo_name = ? OR repo_name = '' OR repo_name IS NULL)
			GROUP BY file_path
		`
		args = []any{repo}
	}

	out := make(map[string]FileHealth)
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return out, err
	}
	defer rows.Close()

	for rows.Next() {
		var path string
		var edits, sigs int
		if err := rows.Scan(&path, &edits, &sigs); err != nil {
			continue
		}
		penalty := edits * 8
		if sigs >= 3 {
			penalty += 5
		}
		if penalty > 100 {
			penalty = 100
		}
		fh := FileHealth{
			FilePath:             path,
			HealthScore:          100 - penalty,
			RecentThrashingCount: edits,
		}
		if edits >= 5 {
			fh.IsFragile = true
			fh.Warning = fmt.Sprintf("%d edits in the last 24h across %d signatures", edits, sigs)
		}
		out[path] = fh
	}
	return out, nil
}

// NodeStat captures aggregate historical stats for a single node signature.
type NodeStat struct {
	Signature   string    `json:"node_signature"`
	FilePath    string    `json:"file_path"`
	EditCount   int       `json:"edit_count"`
	LastAction  string    `json:"last_action"`
	LastModel   string    `json:"last_model"`
	LastEventAt time.Time `json:"last_event_time"`
}

// AllNodeStats queries aggregate metrics for every known AST node signature, optionally filtered by repo_name.
func (s *Store) AllNodeStats(repoFilter ...string) (map[string]NodeStat, error) {
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}

	var query string
	var args []any
	if repo == "" {
		query = `
			WITH RankedEvents AS (
				SELECT e.node_signature, e.file_path, e.action, COALESCE(r.model_name, 'unknown') as model_name, e.event_time,
				       ROW_NUMBER() OVER (PARTITION BY e.node_signature ORDER BY e.event_time DESC) as rn,
				       COUNT(*) OVER (PARTITION BY e.node_signature, e.file_path) as edit_count,
				       MAX(e.event_time) OVER (PARTITION BY e.node_signature, e.file_path) as max_event_time
				FROM code_node_events e
				LEFT JOIN agent_runs r ON e.run_id = r.run_id
			)
			SELECT node_signature, file_path, edit_count, action, model_name, max_event_time
			FROM RankedEvents
			WHERE rn = 1
		`
		args = []any{}
	} else {
		query = `
			WITH FilteredEvents AS (
				SELECT e.node_signature, e.file_path, e.action, COALESCE(r.model_name, 'unknown') as model_name, e.event_time
				FROM code_node_events e
				LEFT JOIN agent_runs r ON e.run_id = r.run_id
				WHERE (e.repo_name = ? OR e.repo_name = '' OR e.repo_name IS NULL)
			),
			RankedEvents AS (
				SELECT node_signature, file_path, action, model_name, event_time,
				       ROW_NUMBER() OVER (PARTITION BY node_signature ORDER BY event_time DESC) as rn,
				       COUNT(*) OVER (PARTITION BY node_signature, file_path) as edit_count,
				       MAX(event_time) OVER (PARTITION BY node_signature, file_path) as max_event_time
				FROM FilteredEvents
			)
			SELECT node_signature, file_path, edit_count, action, model_name, max_event_time
			FROM RankedEvents
			WHERE rn = 1
		`
		args = []any{repo}
	}

	out := make(map[string]NodeStat)
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("node stats query: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var ns NodeStat
		var ts string
		if err := rows.Scan(&ns.Signature, &ns.FilePath, &ns.EditCount, &ns.LastAction, &ns.LastModel, &ts); err != nil {
			return nil, fmt.Errorf("scan node stat: %w", err)
		}
		ns.LastEventAt = parseDBTime(ts)
		out[ns.Signature] = ns
	}
	return out, rows.Err()
}

// nullable returns a sql.Scanner that writes through to s when the column is
// NULL-safe (empty string means NULL in our schema).
func nullable(s *string) *nullString { return &nullString{s: s} }

type nullString struct{ s *string }

func (n *nullString) Scan(v any) error {
	if v == nil {
		*n.s = ""
		return nil
	}
	switch t := v.(type) {
	case string:
		*n.s = t
	case []byte:
		*n.s = string(t)
	default:
		return fmt.Errorf("nullString: unsupported type %T", v)
	}
	return nil
}

func toInt(v any) int {
	switch t := v.(type) {
	case int64:
		return int(t)
	case int:
		return t
	case float64:
		return int(t)
	}
	return 0
}

func toFloat(v any) float64 {
	switch t := v.(type) {
	case float64:
		return t
	case int64:
		return float64(t)
	case int:
		return float64(t)
	}
	return 0
}

// RuntimeTraceRecord is the persisted row for runtime execution & profiler events.
type RuntimeTraceRecord struct {
	TraceID       string    `json:"trace_id"`
	RunID         string    `json:"run_id,omitempty"`
	ServiceName   string    `json:"service_name"`
	NodeSignature string    `json:"node_signature,omitempty"`
	FilePath      string    `json:"file_path,omitempty"`
	DurationMs    float64   `json:"duration_ms"`
	CPUUsagePct   float64   `json:"cpu_usage_pct"`
	MemoryBytes   int64     `json:"memory_bytes"`
	StatusCode    int       `json:"status_code"`
	ErrorMsg      string    `json:"error_msg,omitempty"`
	ProfilerType  string    `json:"profiler_type"`
	MetadataJSON  string    `json:"metadata_json,omitempty"`
	Timestamp     time.Time `json:"timestamp"`
}

// ProfilerHotspotRow correlates AST churn with runtime execution latency/memory.
type ProfilerHotspotRow struct {
	NodeSignature string    `json:"node_signature"`
	FilePath      string    `json:"file_path"`
	TraceCount    int       `json:"trace_count"`
	AvgDurationMs float64   `json:"avg_duration_ms"`
	MaxDurationMs float64   `json:"max_duration_ms"`
	TotalErrors   int       `json:"total_errors"`
	LastSeen      time.Time `json:"last_seen"`
}

// ProfilerOverviewRow summarizes runtime profiling and test execution stats.
type ProfilerOverviewRow struct {
	TotalTraces    int     `json:"total_traces"`
	TotalErrors    int     `json:"total_errors"`
	AvgDurationMs  float64 `json:"avg_duration_ms"`
	ActiveServices int     `json:"active_services"`
}

// InsertTrace appends a runtime profiler trace row.
func (s *Store) InsertTrace(t RuntimeTraceRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	const q = `
		INSERT INTO runtime_traces
			(trace_id, run_id, service_name, node_signature, file_path,
			 duration_ms, cpu_usage_pct, memory_bytes, status_code, error_msg,
			 profiler_type, metadata_json, timestamp)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
	`
	var runID any
	if t.RunID != "" {
		runID = t.RunID
	}
	_, err := s.db.ExecContext(ctx, q,
		t.TraceID, runID, t.ServiceName, t.NodeSignature, t.FilePath,
		t.DurationMs, t.CPUUsagePct, t.MemoryBytes, t.StatusCode, t.ErrorMsg,
		t.ProfilerType, t.MetadataJSON, fmtDBTime(t.Timestamp),
	)
	if err != nil {
		return fmt.Errorf("insert trace %s: %w", t.TraceID, err)
	}
	return nil
}

// RecentTraces returns the N most recent runtime trace events.
func (s *Store) RecentTraces(limit int) ([]RuntimeTraceRecord, error) {
	if limit <= 0 {
		limit = 50
	}
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, `
		SELECT trace_id, COALESCE(run_id, ''), service_name, COALESCE(node_signature, ''),
		       COALESCE(file_path, ''), duration_ms, cpu_usage_pct, memory_bytes,
		       status_code, COALESCE(error_msg, ''), profiler_type, COALESCE(metadata_json, '{}'),
		       timestamp
		FROM runtime_traces
		ORDER BY timestamp DESC
		LIMIT ?
	`, limit)
	if err != nil {
		return nil, fmt.Errorf("recent traces: %w", err)
	}
	defer rows.Close()

	out := make([]RuntimeTraceRecord, 0, limit)
	for rows.Next() {
		var (
			t  RuntimeTraceRecord
			ts string
		)
		if err := rows.Scan(&t.TraceID, &t.RunID, &t.ServiceName, &t.NodeSignature,
			&t.FilePath, &t.DurationMs, &t.CPUUsagePct, &t.MemoryBytes,
			&t.StatusCode, &t.ErrorMsg, &t.ProfilerType, &t.MetadataJSON, &ts); err != nil {
			return nil, fmt.Errorf("scan recent trace: %w", err)
		}
		t.Timestamp = parseDBTime(ts)
		out = append(out, t)
	}
	return out, rows.Err()
}

// ProfilerHotspots returns hotspot functions ranked by average execution duration and errors.
func (s *Store) ProfilerHotspots(limit int) ([]ProfilerHotspotRow, error) {
	if limit <= 0 {
		limit = 25
	}
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	rows, err := s.db.QueryContext(ctx, `
		SELECT node_signature, file_path, COUNT(*) AS trace_count,
		       AVG(duration_ms) AS avg_duration, MAX(duration_ms) AS max_duration,
		       SUM(CASE WHEN status_code >= 400 OR error_msg != '' THEN 1 ELSE 0 END) AS total_errors,
		       MAX(timestamp) AS last_seen
		FROM runtime_traces
		WHERE node_signature != ''
		GROUP BY node_signature, file_path
		ORDER BY avg_duration DESC, trace_count DESC
		LIMIT ?
	`, limit)
	if err != nil {
		return nil, fmt.Errorf("profiler hotspots: %w", err)
	}
	defer rows.Close()

	var out []ProfilerHotspotRow
	for rows.Next() {
		var (
			h  ProfilerHotspotRow
			ts string
		)
		if err := rows.Scan(&h.NodeSignature, &h.FilePath, &h.TraceCount, &h.AvgDurationMs, &h.MaxDurationMs, &h.TotalErrors, &ts); err != nil {
			return nil, fmt.Errorf("scan hotspot: %w", err)
		}
		h.LastSeen = parseDBTime(ts)
		out = append(out, h)
	}
	return out, rows.Err()
}

// ProfilerOverview returns summary stats across all recorded runtime traces.
func (s *Store) ProfilerOverview() (ProfilerOverviewRow, error) {
	var o ProfilerOverviewRow
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	row := s.db.QueryRowContext(ctx, `
		SELECT
			COUNT(*),
			COALESCE(SUM(CASE WHEN status_code >= 400 OR error_msg != '' THEN 1 ELSE 0 END), 0),
			COALESCE(AVG(duration_ms), 0.0),
			COUNT(DISTINCT service_name)
		FROM runtime_traces
	`)
	if err := row.Scan(&o.TotalTraces, &o.TotalErrors, &o.AvgDurationMs, &o.ActiveServices); err != nil {
		return o, fmt.Errorf("profiler overview scan: %w", err)
	}
	return o, nil
}

// FileReadRecord is the persisted form of a file read event.
type FileReadRecord struct {
	ReadID         string    `json:"read_id"`
	RunID          string    `json:"run_id,omitempty"`
	SessionID      string    `json:"session_id,omitempty"`
	RepoName       string    `json:"repo_name"`
	FilePath       string    `json:"file_path"`
	AgentName      string    `json:"agent_name"`
	ModelName      string    `json:"model_name"`
	Provider       string    `json:"provider"`
	ToolName       string    `json:"tool_name"`
	StartLine      int       `json:"start_line"`
	EndLine        int       `json:"end_line"`
	LinesReadCount int       `json:"lines_read_count"`
	PromptTokens   int64     `json:"prompt_tokens"`
	CachedTokens   int64     `json:"cached_tokens"`
	CostUSD        float64   `json:"cost_usd"`
	Intent         string    `json:"intent,omitempty"`
	ReadTime       time.Time `json:"read_time"`
}

// LineReadHeatmap represents aggregated read activity for a slice or line range.
type LineReadHeatmap struct {
	StartLine int `json:"start_line"`
	EndLine   int `json:"end_line"`
	ReadCount int `json:"read_count"`
}

// FileReadStats summarizes all read telemetry for a given file.
type FileReadStats struct {
	FilePath          string           `json:"file_path"`
	TotalReads        int              `json:"total_reads"`
	TotalLinesRead    int              `json:"total_lines_read"`
	TotalCostUSD      float64          `json:"total_cost_usd"`
	TotalPromptTokens int64            `json:"total_prompt_tokens"`
	TotalCachedTokens int64            `json:"total_cached_tokens"`
	UniqueModels      int              `json:"unique_models"`
	ModelBreakdown    map[string]int   `json:"model_breakdown"`
	ProviderBreakdown map[string]int   `json:"provider_breakdown"`
	RecentReads       []FileReadRecord `json:"recent_reads"`
}

// InsertReadEvent records a file read event into file_read_events.
func (s *Store) InsertReadEvent(r FileReadRecord) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	if r.StartLine <= 0 {
		r.StartLine = 1
	}
	if r.LinesReadCount <= 0 && r.EndLine >= r.StartLine {
		r.LinesReadCount = r.EndLine - r.StartLine + 1
	}

	const q = `
		INSERT INTO file_read_events (
			read_id, run_id, session_id, repo_name, file_path, agent_name,
			model_name, provider, tool_name, start_line, end_line,
			lines_read_count, prompt_tokens, cached_tokens, cost_usd,
			intent, read_time
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, COALESCE(?, CURRENT_TIMESTAMP))
		ON CONFLICT(read_id) DO NOTHING
	`
	_, err := s.db.ExecContext(ctx, q,
		r.ReadID, r.RunID, r.SessionID, r.RepoName, r.FilePath, r.AgentName,
		r.ModelName, r.Provider, r.ToolName, r.StartLine, r.EndLine,
		r.LinesReadCount, r.PromptTokens, r.CachedTokens, r.CostUSD,
		r.Intent, fmtDBTime(r.ReadTime),
	)
	return err
}

// GetRecentFileReads returns the most recent file read events, optionally filtered by repo_name.
func (s *Store) GetRecentFileReads(limit int, repoFilter ...string) ([]FileReadRecord, error) {
	if limit <= 0 {
		limit = 50
	}
	var repo string
	if len(repoFilter) > 0 {
		repo = repoFilter[0]
	}

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	var query string
	var args []any
	if repo == "" {
		query = `
			SELECT read_id, COALESCE(run_id, ''), COALESCE(session_id, ''), repo_name, file_path,
			       agent_name, model_name, provider, tool_name, start_line, end_line,
			       lines_read_count, prompt_tokens, cached_tokens, cost_usd, COALESCE(intent, ''),
			       COALESCE(read_time, CURRENT_TIMESTAMP)
			FROM file_read_events
			ORDER BY read_time DESC
			LIMIT ?
		`
		args = []any{limit}
	} else {
		query = `
			SELECT read_id, COALESCE(run_id, ''), COALESCE(session_id, ''), repo_name, file_path,
			       agent_name, model_name, provider, tool_name, start_line, end_line,
			       lines_read_count, prompt_tokens, cached_tokens, cost_usd, COALESCE(intent, ''),
			       COALESCE(read_time, CURRENT_TIMESTAMP)
			FROM file_read_events
			WHERE (repo_name = ? OR repo_name = '' OR repo_name IS NULL)
			ORDER BY read_time DESC
			LIMIT ?
		`
		args = []any{repo, limit}
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("query recent reads: %w", err)
	}
	defer rows.Close()

	var out []FileReadRecord
	for rows.Next() {
		var (
			rec FileReadRecord
			ts  string
		)
		if err := rows.Scan(
			&rec.ReadID, &rec.RunID, &rec.SessionID, &rec.RepoName, &rec.FilePath,
			&rec.AgentName, &rec.ModelName, &rec.Provider, &rec.ToolName,
			&rec.StartLine, &rec.EndLine, &rec.LinesReadCount,
			&rec.PromptTokens, &rec.CachedTokens, &rec.CostUSD,
			&rec.Intent, &ts,
		); err != nil {
			return nil, fmt.Errorf("scan read event: %w", err)
		}
		rec.ReadTime = parseDBTime(ts)
		out = append(out, rec)
	}
	return out, rows.Err()
}

// GetFileReadStats returns detailed read counts, model breakdown, and recent reads for a single file.
func (s *Store) GetFileReadStats(filePath string) (FileReadStats, error) {
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	stats := FileReadStats{
		FilePath:          filePath,
		ModelBreakdown:    make(map[string]int),
		ProviderBreakdown: make(map[string]int),
		RecentReads:       make([]FileReadRecord, 0),
	}

	normPath := strings.ReplaceAll(filePath, "\\", "/")

	// 1. Overall Aggregates
	row := s.db.QueryRowContext(ctx, `
		SELECT COUNT(*),
		       COALESCE(SUM(lines_read_count), 0),
		       COALESCE(SUM(cost_usd), 0.0),
		       COALESCE(SUM(prompt_tokens), 0),
		       COALESCE(SUM(cached_tokens), 0),
		       COUNT(DISTINCT model_name)
		FROM file_read_events
		WHERE file_path = ? OR file_path LIKE ? OR REPLACE(file_path, '\', '/') LIKE ?
	`, filePath, "%"+normPath, "%"+normPath)

	if err := row.Scan(
		&stats.TotalReads,
		&stats.TotalLinesRead,
		&stats.TotalCostUSD,
		&stats.TotalPromptTokens,
		&stats.TotalCachedTokens,
		&stats.UniqueModels,
	); err != nil {
		return stats, fmt.Errorf("scan read stats: %w", err)
	}

	// 2. Model Breakdown
	mRows, err := s.db.QueryContext(ctx, `
		SELECT model_name, COUNT(*)
		FROM file_read_events
		WHERE file_path = ? OR file_path LIKE ? OR REPLACE(file_path, '\', '/') LIKE ?
		GROUP BY model_name
		ORDER BY COUNT(*) DESC
	`, filePath, "%"+normPath, "%"+normPath)
	if err == nil {
		for mRows.Next() {
			var model string
			var count int
			if err := mRows.Scan(&model, &count); err == nil && model != "" {
				stats.ModelBreakdown[model] = count
			}
		}
		_ = mRows.Close()
	}

	// 3. Provider Breakdown
	pRows, err := s.db.QueryContext(ctx, `
		SELECT provider, COUNT(*)
		FROM file_read_events
		WHERE file_path = ? OR file_path LIKE ? OR REPLACE(file_path, '\', '/') LIKE ?
		GROUP BY provider
		ORDER BY COUNT(*) DESC
	`, filePath, "%"+normPath, "%"+normPath)
	if err == nil {
		for pRows.Next() {
			var prov string
			var count int
			if err := pRows.Scan(&prov, &count); err == nil && prov != "" {
				stats.ProviderBreakdown[prov] = count
			}
		}
		_ = pRows.Close()
	}

	// 4. Recent Reads
	rRows, err := s.db.QueryContext(ctx, `
		SELECT read_id, COALESCE(run_id, ''), COALESCE(session_id, ''), repo_name, file_path,
		       agent_name, model_name, provider, tool_name, start_line, end_line,
		       lines_read_count, prompt_tokens, cached_tokens, cost_usd, COALESCE(intent, ''),
		       COALESCE(read_time, CURRENT_TIMESTAMP)
		FROM file_read_events
		WHERE file_path = ? OR file_path LIKE ? OR REPLACE(file_path, '\', '/') LIKE ?
		ORDER BY read_time DESC
		LIMIT 20
	`, filePath, "%"+normPath, "%"+normPath)
	if err == nil {
		for rRows.Next() {
			var (
				rec FileReadRecord
				ts  string
			)
			if err := rRows.Scan(
				&rec.ReadID, &rec.RunID, &rec.SessionID, &rec.RepoName, &rec.FilePath,
				&rec.AgentName, &rec.ModelName, &rec.Provider, &rec.ToolName,
				&rec.StartLine, &rec.EndLine, &rec.LinesReadCount,
				&rec.PromptTokens, &rec.CachedTokens, &rec.CostUSD,
				&rec.Intent, &ts,
			); err == nil {
				rec.ReadTime = parseDBTime(ts)
				stats.RecentReads = append(stats.RecentReads, rec)
			}
		}
		_ = rRows.Close()
	}

	return stats, nil
}

// GetFileReadHeatmap computes line-range frequencies for inspecting hot read regions.
func (s *Store) GetFileReadHeatmap(filePath string) ([]LineReadHeatmap, error) {
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	normPath := strings.ReplaceAll(filePath, "\\", "/")
	rows, err := s.db.QueryContext(ctx, `
		SELECT start_line, end_line, COUNT(*)
		FROM file_read_events
		WHERE (file_path = ? OR file_path LIKE ? OR REPLACE(file_path, '\', '/') LIKE ?)
		  AND (start_line > 0 OR end_line > 0)
		GROUP BY start_line, end_line
		ORDER BY COUNT(*) DESC
		LIMIT 50
	`, filePath, "%"+normPath, "%"+normPath)
	if err != nil {
		return nil, fmt.Errorf("read heatmap query: %w", err)
	}
	defer rows.Close()

	var out []LineReadHeatmap
	for rows.Next() {
		var hm LineReadHeatmap
		if err := rows.Scan(&hm.StartLine, &hm.EndLine, &hm.ReadCount); err != nil {
			return nil, fmt.Errorf("scan read heatmap: %w", err)
		}
		out = append(out, hm)
	}
	return out, rows.Err()
}

// ClearStale prunes old telemetry records older than N days across all analytical tables.
func (s *Store) ClearStale(days int) (int64, error) {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	cutoff := time.Now().UTC().AddDate(0, 0, -days).Format(time.DateTime)

	// All four deletes run in ONE transaction: with per-statement implicit
	// transactions a mid-flight failure committed a partial prune while the
	// API still reported an error — an inconsistent state that is hard to
	// reason about afterwards.
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return 0, fmt.Errorf("clear stale: begin: %w", err)
	}
	defer tx.Rollback()

	var totalDeleted int64
	steps := []struct {
		name string
		sql  string
	}{
		{"code_node_events", "DELETE FROM code_node_events WHERE event_time < ?"},
		{"runtime_traces", "DELETE FROM runtime_traces WHERE timestamp < ?"},
		{"file_read_events", "DELETE FROM file_read_events WHERE read_time < ?"},
		{"agent_runs", `
			DELETE FROM agent_runs
			WHERE created_at < ?
			  AND run_id NOT IN (SELECT DISTINCT run_id FROM code_node_events WHERE run_id IS NOT NULL)
			  AND run_id NOT IN (SELECT DISTINCT run_id FROM runtime_traces WHERE run_id IS NOT NULL)
			  AND run_id NOT IN (SELECT DISTINCT run_id FROM file_read_events WHERE run_id IS NOT NULL)
		`},
	}
	for _, step := range steps {
		res, err := tx.ExecContext(ctx, step.sql, cutoff)
		if err != nil {
			return 0, fmt.Errorf("clear %s: %w", step.name, err)
		}
		if n, _ := res.RowsAffected(); n > 0 {
			totalDeleted += n
		}
	}

	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("clear stale: commit: %w", err)
	}
	return totalDeleted, nil
}

// Vacuum defragments and reclaims unused disk pages in SQLite.
func (s *Store) Vacuum() error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	_, err := s.db.ExecContext(context.Background(), "VACUUM")
	return err
}

// SymbolHistoryRecord joins code_node_events with agent_runs for full timeline and evolution inspection.
type SymbolHistoryRecord struct {
	EventID          string    `json:"event_id"`
	RunID            string    `json:"run_id"`
	RepoName         string    `json:"repo_name"`
	FilePath         string    `json:"file_path"`
	Signature        string    `json:"node_signature"`
	NodeType         string    `json:"node_type"`
	Action           string    `json:"action"`
	BodyHash         string    `json:"ast_content_hash"`
	LOC              int       `json:"lines_of_code"`
	StartLine        uint32    `json:"start_line"`
	EndLine          uint32    `json:"end_line"`
	DiffSnippet      string    `json:"diff_snippet"`
	AddedLines       int       `json:"added_lines"`
	DeletedLines     int       `json:"deleted_lines"`
	OccurredAt       time.Time `json:"event_time"`
	AgentName        string    `json:"agent_name"`
	ModelName        string    `json:"model_name"`
	Provider         string    `json:"provider"`
	Intent           string    `json:"intent"`
	PromptTokens     int64     `json:"prompt_tokens"`
	CompletionTokens int64     `json:"completion_tokens"`
	CostUSD          float64   `json:"cost_usd"`
}

// SymbolHistory returns the chronological revision history of a specific AST symbol / node or all symbols in a file.
func (s *Store) SymbolHistory(filePath, signature string, limit int) ([]SymbolHistoryRecord, error) {
	if limit <= 0 {
		limit = 100
	}
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	normSlash := strings.ReplaceAll(strings.TrimSpace(filePath), "\\", "/")
	normSlash = strings.TrimPrefix(normSlash, "./")

	cleanSig := strings.TrimSpace(signature)
	if idx := strings.Index(cleanSig, "("); idx != -1 {
		cleanSig = strings.TrimSpace(cleanSig[:idx])
	}
	cleanSig = strings.TrimPrefix(cleanSig, "*")
	if idx := strings.LastIndex(cleanSig, "."); idx != -1 {
		// e.g. "Engine.LockFile" -> try matching "LockFile" or full
	}

	var query string
	var args []any

	if normSlash != "" && cleanSig != "" {
		query = `
			SELECT e.event_id, COALESCE(e.run_id, ''), e.repo_name, e.file_path, e.node_signature, e.node_type,
			       e.action, COALESCE(e.ast_content_hash, ''), COALESCE(e.lines_of_code, 0),
			       COALESCE(e.start_line, 0), COALESCE(e.end_line, 0), COALESCE(e.diff_snippet, ''),
			       COALESCE(e.added_lines, 0), COALESCE(e.deleted_lines, 0), e.event_time,
			       COALESCE(r.agent_name, ''), COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''),
			       COALESCE(r.intent, ''), COALESCE(r.prompt_tokens, 0), COALESCE(r.completion_tokens, 0),
			       COALESCE(r.cost_usd, 0.0)
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE (e.file_path = ? OR REPLACE(e.file_path, '\', '/') = ? OR REPLACE(e.file_path, '\', '/') LIKE '%' || ? OR ? LIKE '%' || REPLACE(e.file_path, '\', '/') OR LOWER(REPLACE(e.file_path, '\', '/')) LIKE '%' || LOWER(?))
			  AND (e.node_signature = ? OR LOWER(e.node_signature) = LOWER(?) OR LOWER(e.node_signature) LIKE '%' || LOWER(?) || '%' OR LOWER(e.node_signature) LIKE '%::' || LOWER(?) OR LOWER(e.node_signature) LIKE '%:' || LOWER(?))
			ORDER BY e.event_time ASC
			LIMIT ?
		`
		args = []any{filePath, normSlash, normSlash, normSlash, normSlash, cleanSig, cleanSig, cleanSig, cleanSig, cleanSig, limit}
	} else if normSlash != "" {
		query = `
			SELECT e.event_id, COALESCE(e.run_id, ''), e.repo_name, e.file_path, e.node_signature, e.node_type,
			       e.action, COALESCE(e.ast_content_hash, ''), COALESCE(e.lines_of_code, 0),
			       COALESCE(e.start_line, 0), COALESCE(e.end_line, 0), COALESCE(e.diff_snippet, ''),
			       COALESCE(e.added_lines, 0), COALESCE(e.deleted_lines, 0), e.event_time,
			       COALESCE(r.agent_name, ''), COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''),
			       COALESCE(r.intent, ''), COALESCE(r.prompt_tokens, 0), COALESCE(r.completion_tokens, 0),
			       COALESCE(r.cost_usd, 0.0)
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE (e.file_path = ? OR REPLACE(e.file_path, '\', '/') = ? OR REPLACE(e.file_path, '\', '/') LIKE '%' || ? OR ? LIKE '%' || REPLACE(e.file_path, '\', '/') OR LOWER(REPLACE(e.file_path, '\', '/')) LIKE '%' || LOWER(?))
			ORDER BY e.event_time ASC
			LIMIT ?
		`
		args = []any{filePath, normSlash, normSlash, normSlash, normSlash, limit}
	} else if cleanSig != "" {
		query = `
			SELECT e.event_id, COALESCE(e.run_id, ''), e.repo_name, e.file_path, e.node_signature, e.node_type,
			       e.action, COALESCE(e.ast_content_hash, ''), COALESCE(e.lines_of_code, 0),
			       COALESCE(e.start_line, 0), COALESCE(e.end_line, 0), COALESCE(e.diff_snippet, ''),
			       COALESCE(e.added_lines, 0), COALESCE(e.deleted_lines, 0), e.event_time,
			       COALESCE(r.agent_name, ''), COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''),
			       COALESCE(r.intent, ''), COALESCE(r.prompt_tokens, 0), COALESCE(r.completion_tokens, 0),
			       COALESCE(r.cost_usd, 0.0)
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			WHERE (e.node_signature = ? OR LOWER(e.node_signature) = LOWER(?) OR LOWER(e.node_signature) LIKE '%' || LOWER(?) || '%' OR LOWER(e.node_signature) LIKE '%::' || LOWER(?) OR LOWER(e.node_signature) LIKE '%:' || LOWER(?))
			ORDER BY e.event_time ASC
			LIMIT ?
		`
		args = []any{cleanSig, cleanSig, cleanSig, cleanSig, cleanSig, limit}
	} else {
		query = `
			SELECT e.event_id, COALESCE(e.run_id, ''), e.repo_name, e.file_path, e.node_signature, e.node_type,
			       e.action, COALESCE(e.ast_content_hash, ''), COALESCE(e.lines_of_code, 0),
			       COALESCE(e.start_line, 0), COALESCE(e.end_line, 0), COALESCE(e.diff_snippet, ''),
			       COALESCE(e.added_lines, 0), COALESCE(e.deleted_lines, 0), e.event_time,
			       COALESCE(r.agent_name, ''), COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''),
			       COALESCE(r.intent, ''), COALESCE(r.prompt_tokens, 0), COALESCE(r.completion_tokens, 0),
			       COALESCE(r.cost_usd, 0.0)
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
			ORDER BY e.event_time DESC
			LIMIT ?
		`
		args = []any{limit}
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("symbol history: %w", err)
	}
	defer rows.Close()

	out := make([]SymbolHistoryRecord, 0, 16)
	for rows.Next() {
		var (
			rec SymbolHistoryRecord
			ts  string
		)
		if err := rows.Scan(
			&rec.EventID, &rec.RunID, &rec.RepoName, &rec.FilePath, &rec.Signature, &rec.NodeType,
			&rec.Action, &rec.BodyHash, &rec.LOC,
			&rec.StartLine, &rec.EndLine, &rec.DiffSnippet,
			&rec.AddedLines, &rec.DeletedLines, &ts,
			&rec.AgentName, &rec.ModelName, &rec.Provider,
			&rec.Intent, &rec.PromptTokens, &rec.CompletionTokens,
			&rec.CostUSD,
		); err != nil {
			return nil, fmt.Errorf("scan symbol history: %w", err)
		}
		rec.OccurredAt = parseDBTime(ts)
		out = append(out, rec)
	}
	return out, rows.Err()
}

// ModelActivitySummary aggregates read and write operations performed by an AI model on a file.
type ModelActivitySummary struct {
	ModelName      string    `json:"model_name"`
	Provider       string    `json:"provider"`
	ReadCount      int       `json:"read_count"`
	LinesRead      int       `json:"lines_read"`
	ReadTokens     int64     `json:"read_tokens"`
	ReadCostUSD    float64   `json:"read_cost_usd"`
	WriteEvents    int       `json:"write_events"`
	LinesAdded     int       `json:"lines_added"`
	LinesDeleted   int       `json:"lines_deleted"`
	LastActivityAt time.Time `json:"last_activity_at"`
}

// FileModelActivity returns per-model read and write statistics for a target file.
func (s *Store) FileModelActivity(filePath string) ([]ModelActivitySummary, error) {
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	normSlash := strings.ReplaceAll(strings.TrimSpace(filePath), "\\", "/")
	normSlash = strings.TrimPrefix(normSlash, "./")
	activityMap := make(map[string]*ModelActivitySummary)

	// 1. Read operations per model
	readQuery := `
		SELECT model_name, provider, COUNT(*), COALESCE(SUM(lines_read_count), 0),
		       COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(cost_usd), 0.0), MAX(read_time)
		FROM file_read_events
		WHERE (file_path = ? OR REPLACE(file_path, '\', '/') = ? OR REPLACE(file_path, '\', '/') LIKE '%' || ? OR ? LIKE '%' || REPLACE(file_path, '\', '/') OR LOWER(REPLACE(file_path, '\', '/')) LIKE '%' || LOWER(?))
		GROUP BY model_name
	`
	rRows, err := s.db.QueryContext(ctx, readQuery, filePath, normSlash, normSlash, normSlash, normSlash)
	if err == nil {
		defer rRows.Close()
		for rRows.Next() {
			var (
				model, prov, maxTime string
				count, linesRead     int
				tokens               int64
				cost                 float64
			)
			if err := rRows.Scan(&model, &prov, &count, &linesRead, &tokens, &cost, &maxTime); err == nil {
				t := parseDBTime(maxTime)
				activityMap[model] = &ModelActivitySummary{
					ModelName:      model,
					Provider:       prov,
					ReadCount:      count,
					LinesRead:      linesRead,
					ReadTokens:     tokens,
					ReadCostUSD:    cost,
					LastActivityAt: t,
				}
			}
		}
	}

	// 2. Write / AST mutation operations per model
	writeQuery := `
		SELECT COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''), COUNT(e.event_id),
		       COALESCE(SUM(e.added_lines), 0), COALESCE(SUM(e.deleted_lines), 0), MAX(e.event_time)
		FROM code_node_events e
		LEFT JOIN agent_runs r ON e.run_id = r.run_id
		WHERE (e.file_path = ? OR REPLACE(e.file_path, '\', '/') = ? OR REPLACE(e.file_path, '\', '/') LIKE '%' || ? OR ? LIKE '%' || REPLACE(e.file_path, '\', '/') OR LOWER(REPLACE(e.file_path, '\', '/')) LIKE '%' || LOWER(?))
		GROUP BY r.model_name
	`
	wRows, err := s.db.QueryContext(ctx, writeQuery, filePath, normSlash, normSlash, normSlash, normSlash)
	if err == nil {
		defer wRows.Close()
		for wRows.Next() {
			var (
				model, prov, maxTime      string
				count, linesAdd, linesDel int
			)
			if err := wRows.Scan(&model, &prov, &count, &linesAdd, &linesDel, &maxTime); err == nil {
				t := parseDBTime(maxTime)
				entry, ok := activityMap[model]
				if !ok {
					entry = &ModelActivitySummary{
						ModelName: model,
						Provider:  prov,
					}
					activityMap[model] = entry
				}
				if entry.Provider == "" && prov != "" {
					entry.Provider = prov
				}
				entry.WriteEvents += count
				entry.LinesAdded += linesAdd
				entry.LinesDeleted += linesDel
				if t.After(entry.LastActivityAt) {
					entry.LastActivityAt = t
				}
			}
		}
	}

	out := make([]ModelActivitySummary, 0, len(activityMap))
	for _, entry := range activityMap {
		out = append(out, *entry)
	}
	return out, nil
}

// AllFileModelActivity returns aggregated per-model read and write metrics across all monitored files.
func (s *Store) AllFileModelActivity(limit int) ([]ModelActivitySummary, error) {
	if limit <= 0 {
		limit = 50
	}
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	activityMap := make(map[string]*ModelActivitySummary)

	// 1. Read operations per model
	readQuery := `
		SELECT model_name, provider, COUNT(*), COALESCE(SUM(lines_read_count), 0),
		       COALESCE(SUM(prompt_tokens), 0), COALESCE(SUM(cost_usd), 0.0), MAX(read_time)
		FROM file_read_events
		GROUP BY model_name
	`
	rRows, err := s.db.QueryContext(ctx, readQuery)
	if err == nil {
		defer rRows.Close()
		for rRows.Next() {
			var (
				model, prov, maxTime string
				count, linesRead     int
				tokens               int64
				cost                 float64
			)
			if err := rRows.Scan(&model, &prov, &count, &linesRead, &tokens, &cost, &maxTime); err == nil {
				t := parseDBTime(maxTime)
				activityMap[model] = &ModelActivitySummary{
					ModelName:      model,
					Provider:       prov,
					ReadCount:      count,
					LinesRead:      linesRead,
					ReadTokens:     tokens,
					ReadCostUSD:    cost,
					LastActivityAt: t,
				}
			}
		}
	}

	// 2. Write / AST mutation operations per model
	writeQuery := `
		SELECT COALESCE(r.model_name, 'unknown'), COALESCE(r.provider, ''), COUNT(e.event_id),
		       COALESCE(SUM(e.added_lines), 0), COALESCE(SUM(e.deleted_lines), 0), MAX(e.event_time)
		FROM code_node_events e
		LEFT JOIN agent_runs r ON e.run_id = r.run_id
		GROUP BY r.model_name
	`
	wRows, err := s.db.QueryContext(ctx, writeQuery)
	if err == nil {
		defer wRows.Close()
		for wRows.Next() {
			var (
				model, prov, maxTime      string
				count, linesAdd, linesDel int
			)
			if err := wRows.Scan(&model, &prov, &count, &linesAdd, &linesDel, &maxTime); err == nil {
				t := parseDBTime(maxTime)
				entry, ok := activityMap[model]
				if !ok {
					entry = &ModelActivitySummary{
						ModelName: model,
						Provider:  prov,
					}
					activityMap[model] = entry
				}
				if entry.Provider == "" && prov != "" {
					entry.Provider = prov
				}
				entry.WriteEvents += count
				entry.LinesAdded += linesAdd
				entry.LinesDeleted += linesDel
				if t.After(entry.LastActivityAt) {
					entry.LastActivityAt = t
				}
			}
		}
	}

	out := make([]ModelActivitySummary, 0, len(activityMap))
	for _, entry := range activityMap {
		out = append(out, *entry)
	}
	return out, nil
}

// ModelFrictionEdge represents a directed friction / collision between an author model and an overwriter model.
type ModelFrictionEdge struct {
	AuthorModel     string  `json:"author_model"`
	OverwriterModel string  `json:"overwriter_model"`
	ConflictCount   int     `json:"conflict_count"`
	LinesModified   int     `json:"lines_modified"`
	LinesDeleted    int     `json:"lines_deleted"`
	SelfThrash      bool    `json:"is_self_thrash"`
	WastedCostUSD   float64 `json:"wasted_cost_usd"`
}

// CrossThrashEvent is an individual record of one model modifying or deleting code authored by another model (or itself).
type CrossThrashEvent struct {
	EventID          string    `json:"event_id"`
	FilePath         string    `json:"file_path"`
	Signature        string    `json:"node_signature"`
	Action           string    `json:"action"`
	AuthorModel      string    `json:"author_model"`
	AuthorRunID      string    `json:"author_run_id"`
	AuthorTime       time.Time `json:"author_time"`
	OverwriterModel  string    `json:"overwriter_model"`
	OverwriterRunID  string    `json:"overwriter_run_id"`
	OverwriterTime   time.Time `json:"overwriter_time"`
	TimeDeltaSeconds int64     `json:"time_delta_seconds"`
	AddedLines       int       `json:"added_lines"`
	DeletedLines     int       `json:"deleted_lines"`
	DiffSnippet      string    `json:"diff_snippet"`
	IsCrossAgent     bool      `json:"is_cross_agent"`
}

// InterAgentFrictionReport holds the aggregated collision matrix and the recent cross-thrash events.
type InterAgentFrictionReport struct {
	Edges            []ModelFrictionEdge `json:"edges"`
	RecentCollisions []CrossThrashEvent  `json:"recent_collisions"`
	TotalCollisions  int                 `json:"total_collisions"`
	CrossAgentRatio  float64             `json:"cross_agent_ratio_pct"`
	TopFrictionPair  string              `json:"top_friction_pair"`
}

// ModelFrictionMatrix computes inter-agent code overwrites, deletions, and self-thrash loops.
func (s *Store) ModelFrictionMatrix(limit int) (*InterAgentFrictionReport, error) {
	ctx, cancel := s.withTimeout(context.Background())
	defer cancel()

	if limit <= 0 || limit > 1000 {
		limit = 200
	}

	const q = `
		WITH OrderedEvents AS (
			SELECT 
				e.event_id,
				e.file_path,
				e.node_signature,
				e.action,
				COALESCE(e.added_lines, 0) AS added_lines,
				COALESCE(e.deleted_lines, 0) AS deleted_lines,
				COALESCE(e.diff_snippet, '') AS diff_snippet,
				e.event_time,
				COALESCE(r.model_name, 'unknown') AS overwriter_model,
				COALESCE(r.run_id, '') AS overwriter_run_id,
				LAG(COALESCE(r.model_name, 'unknown')) OVER (PARTITION BY e.file_path, e.node_signature ORDER BY e.event_time) AS author_model,
				LAG(COALESCE(r.run_id, '')) OVER (PARTITION BY e.file_path, e.node_signature ORDER BY e.event_time) AS author_run_id,
				LAG(e.event_time) OVER (PARTITION BY e.file_path, e.node_signature ORDER BY e.event_time) AS author_time
			FROM code_node_events e
			LEFT JOIN agent_runs r ON e.run_id = r.run_id
		)
		SELECT 
			event_id, file_path, node_signature, action, added_lines, deleted_lines,
			diff_snippet, event_time, overwriter_model, overwriter_run_id,
			author_model, author_run_id, author_time
		FROM OrderedEvents
		WHERE author_model IS NOT NULL AND action IN ('MODIFIED', 'DELETED')
		ORDER BY event_time DESC
		LIMIT ?;
	`

	rows, err := s.db.QueryContext(ctx, q, limit)
	if err != nil {
		return nil, fmt.Errorf("query model friction: %w", err)
	}
	defer rows.Close()

	var (
		events          []CrossThrashEvent
		edgeMap         = make(map[string]*ModelFrictionEdge)
		totalCollisions int
		crossCount      int
		maxPairCount    int
		topPair         string
	)

	for rows.Next() {
		var (
			ev                       CrossThrashEvent
			evTimeStr, authorTimeStr string
			added, deleted           int
		)

		if err := rows.Scan(
			&ev.EventID,
			&ev.FilePath,
			&ev.Signature,
			&ev.Action,
			&added,
			&deleted,
			&ev.DiffSnippet,
			&evTimeStr,
			&ev.OverwriterModel,
			&ev.OverwriterRunID,
			&ev.AuthorModel,
			&ev.AuthorRunID,
			&authorTimeStr,
		); err != nil {
			continue
		}

		ev.AddedLines = added
		ev.DeletedLines = deleted
		ev.OverwriterTime = parseDBTime(evTimeStr)
		ev.AuthorTime = parseDBTime(authorTimeStr)
		if !ev.AuthorTime.IsZero() && !ev.OverwriterTime.IsZero() {
			ev.TimeDeltaSeconds = int64(ev.OverwriterTime.Sub(ev.AuthorTime).Seconds())
		}
		ev.IsCrossAgent = (ev.AuthorModel != ev.OverwriterModel) && ev.AuthorModel != "unknown" && ev.OverwriterModel != "unknown"

		events = append(events, ev)
		totalCollisions++
		if ev.IsCrossAgent {
			crossCount++
		}

		edgeKey := fmt.Sprintf("%s->%s", ev.AuthorModel, ev.OverwriterModel)
		edge, ok := edgeMap[edgeKey]
		if !ok {
			edge = &ModelFrictionEdge{
				AuthorModel:     ev.AuthorModel,
				OverwriterModel: ev.OverwriterModel,
				SelfThrash:      ev.AuthorModel == ev.OverwriterModel,
			}
			edgeMap[edgeKey] = edge
		}
		edge.ConflictCount++
		edge.LinesModified += added
		edge.LinesDeleted += deleted

		if edge.ConflictCount > maxPairCount && ev.AuthorModel != ev.OverwriterModel {
			maxPairCount = edge.ConflictCount
			topPair = fmt.Sprintf("%s ➔ %s (%d collisions)", ev.AuthorModel, ev.OverwriterModel, maxPairCount)
		}
	}

	edges := make([]ModelFrictionEdge, 0, len(edgeMap))
	for _, e := range edgeMap {
		edges = append(edges, *e)
	}

	ratio := 0.0
	if totalCollisions > 0 {
		ratio = (float64(crossCount) / float64(totalCollisions)) * 100.0
	}

	return &InterAgentFrictionReport{
		Edges:            edges,
		RecentCollisions: events,
		TotalCollisions:  totalCollisions,
		CrossAgentRatio:  ratio,
		TopFrictionPair:  topPair,
	}, nil
}
